### ISSUE TITLE
1.9.1 device not supported

### ISSUE THREAD

**Issue by djweinhagen** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#66] opened 2020-12-08 17:44 UTC
When I updated to 1.9.1, it says my device is no longer supported

**Comment by djweinhagen** [comment] 2020-12-08 17:44
My magic home device*

**Comment by Zacknetic** [comment] 2020-12-08 18:18
Hi there,

Please download your log, ensure it has no sensitive information, and upload it here so I can further assist you.
Additionally, give me a purchase link to your device.

**Comment by alert82** [comment] 2020-12-08 19:44
Same here 

Log 

08/12/2020, 20:35:38] [homebridge-magichome-dynamic-platform] 1 -Registering existing accessory...
 Display Name: 'Simple RGB' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'xxxxxxxxx' 
IP-Address: 'Xxxxxxx
Hardware Version: '51' 
Firmware Version: '6' 

[08/12/2020, 20:35:38] [homebridge-magichome-dynamic-platform] platform.ts discoverDevices() accessory creation has thrown the following error: TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor
    at HomebridgeMagichomeDynamicPlatform.registerExistingAccessory (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:404:28)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:159:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  [stack]: 'TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor\n' +
    '    at HomebridgeMagichomeDynamicPlatform.registerExistingAccessory (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:404:28)\n' +
    '    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:159:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
  [message]: 'accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor'
}
[08/12/2020, 20:35:38] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0

**Comment by mik9** [comment] 2020-12-08 22:42
Same exception and hardware. Found [this](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/commit/85c9c5759a088b52e2d1061fa9e663250ee420f1) commit and reverted to 1.8.4. Led strip works fine now. Mine controller is RGB, without W pin.

**Comment by djweinhagen** [comment] 2020-12-09 14:19
09/12/2020, 08:17:37] [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.

[09/12/2020, 08:17:37] [homebridge-magichome-dynamic-platform] 1 -Registering existing accessory...
 Display Name: undefined 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ2101' 
Unique ID: 
IP-Address: xx
Hardware Version: '51' 
Firmware Version: '8' 

[09/12/2020, 08:17:37] [homebridge-magichome-dynamic-platform] platform.ts discoverDevices() accessory creation has thrown the following error: TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor
    at HomebridgeMagichomeDynamicPlatform.registerExistingAccessory (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:404:28)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:159:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  [stack]: 'TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor\n' +
    '    at HomebridgeMagichomeDynamicPlatform.registerExistingAccessory (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:404:28)\n' +
    '    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:159:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
  [message]: 'accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor'
}
[09/12/2020, 08:17:37] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0

**Comment by techo91** [comment] 2020-12-09 14:33
I have the same. I downgraded 1.8.5 and all is good for now but I would be nice to know that the issue is solved.

**Comment by CAuguston** [comment] 2020-12-09 15:10
I am having the same issue as above. I updated to homebridge-magichome-dynamic-platform v1.9.2-alpha6 
and here is my logs.  Hope it gives some info to help.
-----
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] 
Discovered 3 devices.

[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] 1 -Registering existing accessory...
 Display Name: 'LivingRoom LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'DC4F228A18XX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '51' 
Firmware Version: '6' 

[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] [3] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] device object:  {
  UUID: 'f64ea12b-5a32-4f5b-ba01-f253c41a39XX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'LivingRoom LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 123, green: 121, blue: 134 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: 'DC4F228A18XX',
  modelNumber: 'AK001-ZJ2XX',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] 2 -Registering existing accessory...
 Display Name: 'Kitchen LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'DC4F228B9EXX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '51' 
Firmware Version: '6' 

[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] [3] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] device object:  {
  UUID: '5c5d77a0-93fd-4309-a1c5-db06ad1144XX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'Kitchen LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 123, green: 121, blue: 134 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: 'DC4F228B9EXX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] 3 -Registering existing accessory...
 Display Name: 'Bed  LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: '600194B950XX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '51' 
Firmware Version: '6' 

[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] [3] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] device object:  {
  UUID: '34975ffe-f13e-4748-be10-5520631e0cXX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'Bed  LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 82, green: 42, blue: 213 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: '600194B950XX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0

[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] All devices have been updated to latest data model. Disabling periodic device discovery.
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] Online and New: []
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] Online and known: [ 'DC4F228A18XX', 'DC4F228B9EXX', '600194B950XX' ]
[12/9/2020, 10:07:06 AM] [homebridge-magichome-dynamic-platform] Offline and known: []

**Comment by treforparr** [comment] 2020-12-09 15:11
Same it's stopped working not a very good update unitstable

**Comment by Zacknetic** [comment] 2020-12-09 15:39
Hello and thank you for the logs. It has been very helpful. There are two bugs here that we have tracked down. 
The first is a bug was a copy error that changed grb devices to become grbw which does not exist. That has been solved.

As for this error: `TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor`
We are finalizing a fix but want to make absolutely sure it won't break anything before releasing it. 1.9.0 was an attempt to fix many issues but it wasn't tested thoroughly enough. If you aren't having the GRBW issue and wish to use 1.9.1., you can purge your MagicHome accessories, losing automations, names, rooms, and scenes, but it will work properly.

Please note that any alpha / beta versions WILL break your current Homebridge Magichome build. So use them with caution and not as a fix. If you are interested in trying out alphas giving feedback, we'd love your help. Let us know in the MagicHome Discord Server and we'll get you fixed up with a Beta Tester role.

Thank you everyone for your continued patience with this update and with this plugin as a whole. I will keep you informed.

**Comment by Zacknetic** [comment] 2020-12-09 21:52
If you'd like, the beta3 is looking very stable from initial tests. Use with caution however as we have made many changes with very little testing time.

**Comment by CAuguston** [comment] 2020-12-09 23:54
Upgraded to beta 3. Here is the logs. Hope the logs help..  Let me know if I need to purge and try again
--

[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] 1 - Registering existing accessory...
Display Name: 'Bed  LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: '600194B950XX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: '34975ffe-f13e-4748-be10-5520631e0cXX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'Bed  LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 82, green: 42, blue: 213 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: '600194B950XX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] 2 - Registering existing accessory...
Display Name: 'LivingRoom LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'DC4F228A18XX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: 'f64ea12b-5a32-4f5b-ba01-f253c41a39XX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'LivingRoom LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 123, green: 121, blue: 134 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: 'DC4F228A18XX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] 3 - Registering existing accessory...
Display Name: 'Kitchen LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'DC4F228B9EXX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:47:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: '5c5d77a0-93fd-4309-a1c5-db06ad1144XX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'Kitchen LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 123, green: 121, blue: 134 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: 'DC4F228B9EXX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] 1 - Registering existing accessory...
Display Name: 'Bed  LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: '600194B950XX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: '34975ffe-f13e-4748-be10-5520631e0cXX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'Bed  LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 82, green: 42, blue: 213 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: '600194B950XX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] 2 - Registering existing accessory...
Display Name: 'Kitchen LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'DC4F228B9EXX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: '5c5d77a0-93fd-4309-a1c5-db06ad1144XX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'Kitchen LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 123, green: 121, blue: 134 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: 'DC4F228B9EXX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] 3 - Registering existing accessory...
Display Name: 'LivingRoom LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'DC4F228A18XX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:47:41 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: 'f64ea12b-5a32-4f5b-ba01-f253c41a39XX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'LivingRoom LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 123, green: 121, blue: 134 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: 'DC4F228A18XX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] 1 - Registering existing accessory...
Display Name: 'Kitchen LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'DC4F228B9EXX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: '5c5d77a0-93fd-4309-a1c5-db06ad1144XX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'Kitchen LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 123, green: 121, blue: 134 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: 'DC4F228B9EXX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] 2 - Registering existing accessory...
Display Name: 'Bed  LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: '600194B950XX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: '34975ffe-f13e-4748-be10-5520631e0cXX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'Bed  LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 82, green: 42, blue: 213 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: '600194B950XX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}
[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] 3 - Registering existing accessory...
Display Name: 'LivingRoom LED' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ210' 
Unique ID: 'DC4F228A18XX' 
IP-Address: '172.24.0.1XX' 
Hardware Version: '33' 
Firmware Version: '6' 

[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/9/2020, 6:48:11 PM] [homebridge-magichome-dynamic-platform] [registerExistingAccessory] device object:  {
  UUID: 'f64ea12b-5a32-4f5b-ba01-f253c41a39XX',
  cachedIPAddress: '172.24.0.1XX',
  restartsSinceSeen: 0,
  displayName: 'LivingRoom LED',
  lastKnownState: {
    debugBuffer: { type: 'Buffer', data: [Array] },
    controllerHardwareVersion: 51,
    isOn: false,
    RGB: { red: 123, green: 121, blue: 134 },
    whiteValues: { warmWhite: 0, coldWhite: 0 },
    controllerFirmwareVersion: 6
  },
  ipAddress: '172.24.0.1XX',
  uniqueId: 'DC4F228A18XX',
  modelNumber: 'AK001-ZJ210',
  lightParameters: {
    controllerLogicType: 'GRBWStrip',
    convenientName: 'GRBW Strip',
    simultaneousCCT: true,
    hasColor: true,
    hasBrightness: true
  },
  controllerHardwareVersion: 51,
  controllerFirmwareVersion: 6
}

**Comment by Zacknetic** [comment] 2020-12-10 00:16
Okay yes this helps tremendously. The program isn’t looking for that specific error... I’ll add that to the next beta so look out for it. We’re planning on a non beta release Friday morning EST.

**Comment by isramos** [comment] 2020-12-10 02:08
@CAuguston would you say your 'LivingRoom LED' has white?  In other words,  I wonder if it's an RGB or RGBW.

**Comment by isramos** [comment] 2020-12-10 03:20
The release 1.9.2-alpha8 now available in npm (and upcoming 1.9.2-beta4 and 1.9.2 latest) fixes this issue.

The root cause is that we renamed `GRBWStrip` to `GRBStrip` better reflect the nature of the device. But that renaming broke the cached data.  In our latest code, every start-up we validate that cached data and update it as needed.

**Comment by Zacknetic** [comment] 2020-12-10 18:20
@CAuguston @techo91 
@mik9 @djweinhagen 
Reopening to ensure that the problem has been solved.

> The release 1.9.2-alpha8 now available in npm (and upcoming 1.9.2-beta4 and 1.9.2 latest) fixes this issue.
> 
> The root cause is that we renamed `GRBWStrip` to `GRBStrip` better reflect the nature of the device. But that renaming broke the cached data. In our latest code, every start-up we validate that cached data and update it as needed.

While this is partially true. The root cause of the error was created when GRBStrip was renamed to GRBWStrip. This was a copy error that occurred in v1.9.1. We reverted the name in 1.9.2 beta, however our repair function was unable to catch this difference which resulted in nothing being repaired. @isramos has since added in a great check for this in beta4 so please let me know if that works out for you. Thank you.

**Comment by mik9** [comment] 2020-12-10 18:38
Installed 1.9.2-alpha8, my strip was detected and working fine.

**Comment by treforparr** [comment] 2020-12-10 19:52
I am having problems with the latest update this work as well as the last I figured out that the name had to be what it said on the app on the last update that fix some of the problem and it was working perfectly why change something when it was doesn’t need to change

**Comment by CAuguston** [comment] 2020-12-10 22:37
v1.9.2-beta4  has solved the issue for me. Thank you. My LED strips are now functional without having to purge them out.

Thanks as always for your help. Very happy with the programmers and community

**Comment by Zacknetic** [comment] 2020-12-11 00:57
Happy to be of service. We plan on officially releasing this version in ~ 12 hours. So keep an eye out. 

With our new beta team we're able to test these updates a few days first. Making things a lot smoother.

**Comment by Zacknetic** [comment] 2020-12-13 23:01
Closing this issue as it was reported solved. Thank you.

**Closed by Zacknetic** 2020-12-13 23:01 UTC
