### ISSUE TITLE
Discovered device did not respond to query

### ISSUE THREAD

**Issue by techo91** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#94] opened 2021-03-12 11:44 UTC
Hi,
I have this log entry on a new installation of Hoobs version: 3.3.3. Node version: 15.10.0
[homebridge-magichome-dynamic-platform] Warning! Discovered device did not respond to query. This is usually due to an unresponsive device.
Please restart homebridge. If the problem persists, ensure the device works in the "Magichome Pro" app.
File an issue on github with an uploaded log. {
  ipAddress: '192.168.xxx.xxx',
  uniqueId: '18B905C0xxxx',
  modelNumber: 'AK001-ZJ2145'

My device responds perfectly in the Magic Home app. I'm not sure how can I diagnose this. Can anyone help me with this?

Thanks.

**Comment by bwp91** [comment] 2021-03-12 11:53
Might not sort this issue but I wouldn’t recommend node version 15. Try downgrading to v14.16.0.

Homebridge doesn’t support odd numbered versions of node

**Comment by techo91** [comment] 2021-03-12 17:47
I tried, unfortunately hoobs 3.3.3 installed in a jail in TrueNAS system (FreeBSD) does not work with older version of node. I'm not sure what the reason is though. Can I try something else?

**Comment by Zacknetic** [comment] 2021-03-12 17:50
Most likely not. The issue is, for some reason, the responses from the devices aren’t reaching the hoobs instance.

This type of setup is outside the scope of this plugin.

My suggestion to you would be to install hoobs / Homebridge in a less locked off environment.

**Comment by bwp91** [comment] 2021-03-12 17:55
Node v14 isn’t an “old” version it’s a very current version. strange that you can’t downgrade?

**Comment by techo91** [comment] 2021-03-12 18:57
I have a sonoff plugin installed as well and it communicates with several different devices without any issue. I can try the docker version a bit later and see how it goes there.

**Comment by bwp91** [comment] 2021-03-12 19:01
Sonoff plugin uses a cloud connection whereas i believe magichome uses a different local connection method.
Worth trying the docker version.
The magichome plugin is a popular plugin and i think there would be a lot of chatter if something was wrong with the plugin with connecting to devices

**Comment by tom-23** [comment] 2021-03-12 19:07
This issue actually helps a lot.

If you look at #88, I had the same issue using macOS. There must be some similarity in the way networking is handled in these UNIX operating systems which is different from Linux or Windows (or we haven't implemented something correctly). I think we need to look into this further...

**Comment by techo91** [comment] 2021-03-12 21:21
I tested the docker version and it looks like the plug-in partially works there. It has node 14.16.0. What works is commands via HomeKit, what doesn’t work is commands via the Hoobs GUI.

**Comment by bwp91** [comment] 2021-03-12 21:46
if it works though homekit it **must** work through the hoobs ui. any log entries when you use the hoobs ui?

**Comment by techo91** [comment] 2021-03-13 09:54
This is my logic as well but strangely it is not the case. The only thing in the log that I can see is this:

[HOOBS 420A@GRB Strip@@Hardware Revision] characteristic was supplied illegal value: number instead of string, supplying illegal values will throw errors in the future
12/03/2021, 22:01:38 [HOOBS 420A@GRB Strip@@Firmware Revision] characteristic was supplied illegal value: number instead of string, supplying illegal values will throw errors in the future
12/03/2021, 22:01:38 [HOOBS 420A@GRB Strip@@Configured Name] Characteristic not in required or optional characteristic section for service Lightbulb. Adding anyway.

When toggling on or off, there are no log messages.

**Comment by Zacknetic** [comment] 2021-07-05 19:46
Could you please update to version 1.9.4. (just released, may take some time to appear on Hoobs). Let me know how that goes.

Thank you
-Z

**Comment by mbinax** [comment] 2021-11-14 23:44
For a long time everything was working well.
Since a few weeks I obtain the same issue described here...

![Screenshot 2021-11-15 at 00 43 00](https://user-images.githubusercontent.com/64318944/141703554-f539441e-9b6a-4a0a-af3c-fb228aa0c3cb.png)

**Comment by Zacknetic** [comment] 2021-11-16 23:24
Hello, please update to version 1.9.7 and ensure you are upgraded to node 16. This should fix your issues.

Please let me know.
-z

**Comment by mbinax** [comment] 2021-11-19 01:15
> Hello, please update to version 1.9.7 and ensure you are upgraded to node 16. This should fix your issues.
> 
> Please let me know. -z

Yeah! That's right! It works.
Thank you so much ;-)

**Comment by Zacknetic** [comment] 2021-12-09 20:39
@mbinax great to hear it!

Closing this issue as solved.

**Closed by Zacknetic** 2021-12-09 20:39 UTC
