### ISSUE TITLE
Plugin not working with HOOBS

### ISSUE THREAD

**Issue by LubosCzech** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#11] opened 2020-07-18 13:44 UTC
I found this in log:
`The requested platform "homebridge-magichome-dynamic-platform" was not registered by any plugin.`
And:
`Your config.json is requesting the platform "homebridge-magichome-dynamic-platform" which has not been published by any installed plugins.
`
Plugin is installed and I can see it in HOOBS and configure it and it is loaded.
`Loaded plugin "homebridge-magichome-dynamic-platform".`

**Comment by Zacknetic** [comment] 2020-07-18 18:59
Hi, thank you for bringing this to my attention. I am unfamiliar with HOOBS but I just did a little preliminary research.

I suggest you uninstall their version of homebridge and reinstall to the lastest version by following [this](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian) tutorial. Then use config ui x to install my plugin.

Most likely HOOBS is using some branched or older version of homebridge that is incompatible with my plugin. Thus a dynamic-plugin will not work correctly on it.

Please let me know if this is something you'd like to do and if you have any questions. Please keep in mind that I have zero experience with HOOBS. I cannot be held responsible if it starts acting wonky after you modify it.

**Comment by Zacknetic** [comment] 2020-07-21 06:58
@LubosCzech my co-collaborator @tom-23 has some experience in this and will provide you with some alternative advice in this matter. Look out for his comment here soon.

**Comment by tom-23** [comment] 2020-07-22 22:41
Hey, @LubosCzech, sorry for the late reply but do you have a full log.txt you can provide with the error occurring? This seems to me like you have some sort of installation error. Did you install the plugin using the WebUI? Thanks, Tom

**Comment by csmarshall** [comment] 2020-07-30 19:35
*bump?* What data do you need for Hoobs?

**Comment by tom-23** [comment] 2020-08-14 20:28
Did you install the plugin using the HOOBS UI or via the command line? It could be possible that you didn't install the plugin globally or something.

**Comment by galzil** [comment] 2020-09-02 14:32
I have the same problem, this is a common issue

I've found a related issue [here ](https://github.com/hjdhjd/homebridge-myq2/issues/63)stating that a simple fix is changing
api.registerPlatform(PLATFORM_NAME, ScreenLogicPlatform)
to
api.registerPlatform("homebridge-magichome-dynamic-platform", PLATFORM_NAME, ScreenLogicPlatform)

**Comment by FilipePinhoDev** [comment] 2020-09-26 13:33
Any news about this problem?

**Comment by Zacknetic** [comment] 2020-09-26 18:44
> I have the same problem, this is a common issue
> 
> I've found a related issue [here ](https://github.com/hjdhjd/homebridge-myq2/issues/63)stating that a simple fix is changing
> api.registerPlatform(PLATFORM_NAME, ScreenLogicPlatform)
> to
> api.registerPlatform("homebridge-magichome-dynamic-platform", PLATFORM_NAME, ScreenLogicPlatform)

I'll give this a try in my development branch and if it doesn't break anything I will push it to the main branch.

**Comment by Zacknetic** [comment] 2020-09-26 21:47
@LubosCzech @csmarshall @FilipePinhoDev Please update to the latest version. Be sure to purge ALL of your MagicHome devices from Homebridge either by deleting your accessories folder or using my purge feature.

@galzil I have added in your suggestion, hopefully this solves the issue. Thank you.

**Comment by FilipePinhoDev** [comment] 2020-09-27 11:21
@Zacknetic i'm not home at the moment but i updated the plugin in Hoobs remotely, by the logs, it seems to be working, no more `"Your config.json is requesting the platform "homebridge-magichome-dynamic-platform" which has not been published by any installed plugins."` and begins the search.

I'll update you after testing.

Thank you!

**Comment by FilipePinhoDev** [comment] 2020-09-28 19:54
@Zacknetic I just confirmed that with the update, it's working great. No purge or accessory delete was needed in my case. You can close this issue.

Thank you very much!

**Comment by Zacknetic** [comment] 2020-09-28 20:11
Very good to hear. Closing this for now but @LubosCzech if you find your problem has not been solved please reopen this issue.

**Closed by Zacknetic** 2020-09-28 20:11 UTC
Labels: bug
