### ISSUE TITLE
Magic Home non RGB controller

### ISSUE THREAD

**Issue by jasonlifeisguid** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#3] opened 2020-06-05 21:11 UTC
I'm getting an error 'Uknown light version: 2... color probably cannot be set. Trying anyway.'.  These controllers will only fade and are for single color only.   I'm not sure where to grab the log.txt file data from. Is there an attribute I can set in the config to alter the controller type?

A link to the controller on Amazon:
https://www.amazon.com/Sumaote-Controller-Compatible-Assistant-Dimmable/dp/B07JC3L4Z6/ref=pd_sbs_86_5/135-2537846-0843222?_encoding=UTF8&pd_rd_i=B07JC3L4Z6&pd_rd_r=735a14eb-c073-4785-8f51-e8eb966b68e1&pd_rd_w=bygLS&pd_rd_wg=RXHvV&pf_rd_p=d9804894-61b7-40b3-ba58-197116cffd9d&pf_rd_r=Y19CSR1B2WPP54T7ZBB5&psc=1&refRID=Y19CSR1B2WPP54T7ZBB5

**Comment by Zacknetic** [comment] 2020-06-06 00:19
Hi, thank you for posting this issue. The amazon link is helpful as well. Your log will be in your .homebridge folder and might be called homebridge.log. For this particular instance I won't need to see the log because I already know the issue.

Your controller uses a protocol I haven't encountered yet so there is no code for it. If there were, the plugin would automatically assign the correct controller so no config alterations would be necessary.

I do not have this version of the controller so I have no means of testing it, but I will search online to see if there is some existing code that I can implement. I will post back with results and instructions on how to move forward.

**Comment by Zacknetic** [comment] 2020-06-06 05:36
Okay, I have a plan. I have setup an android emulator running the Magic Home app on my computer along with a packet sniffer Wireshark.  In my initial testing, I have confirmed that I can view the TCP packets of a remote MagicHome controller. Luckily the app still uses the same Magic Home protocol regardless of access remotely or local. This should reveal your device's protocol to me.

During my research, I was unable to find a single reference to the Sumaote/MagicHome dimmer protocol. In other MagicHome github repository issues, the authors either suggest flashing the controller's firmware, using a different controller, or don't respond at all... Hopefully our luck will be different.

**What to do next:** In order for me to view your controller, I'll need you to complete the following steps:

**1. Sign into my throwaway MagicHome account in your MagicHome "Pro" app**
- enter iPhone MagicHome "Pro" App>click top-left gear icon>"Sign in or Create an account">input login credentials (shown below)

<details><summary>Click here to view poorly hidden login credentials</summary>
<p>

#### Username
```
magic.home.test@gmail.com
```
#### Password
```
testmagichome
```

</p>
</details>
 

**2. Enable remote control for your device on that account**
- enter iPhone MagicHome "Pro" App>Top Left Gear Icon>Device Settings>click the name of your dimmer i.e. _controller 12345_>Remote Settings>Tap toggle button next to "Remote status">ensure that it can be controlled while iPhone is disconnected from WiFi
 

**3. Change the color of my office light to red and then post here to let me know you're ready**
- I will allow remote access to my office light, which you should be able to see, and will look for the color change in the morning indicating you are ready to roll
 

**4. Give me time to test your device**

I will then be able to view and test your device remotely. Within a day I should find a solution assuming all goes as planned. Don't be alarmed if your lights start changing brightness. Though it should be quick as I simply need to view a few packets.
 

A few final details. In terms of privacy: I will NOT be able to see anything other than the packets sent to and from your LED controller. However anyone that reads this post within the next few days could potentially control yours and my remote access enabled lights.

Let me know when you're setup or if you have further questions.

**Comment by jasonlifeisguid** [comment] 2020-06-07 22:35
I open on of the units and found this that matched exactly.  https://github.com/xoseperez/espurna/issues/1999
Not sure if it will  help at all.  
When I get some time I’ll run through your instructions.  Right now it’s able to turn the device on and off, which is enough for the automation I’m doing.  

Thanks
Jason

**Comment by Zacknetic** [comment] 2020-06-07 22:56
In that post they are reflashing the firmware. They aren’t attempting to learn the device’s original protocol which is how this plugin works. I will close this issue for now. Feel free to reopen it when you’d like to get started troubleshooting.

**Closed** 2020-06-07 23:08 UTC

**Comment by Zacknetic** [comment] 2020-08-05 08:43
@jasonlifeisguid Just to let you know, I've added functionality for magichome dimmers, give it a try and let me know how it goes.

**Comment by jasonlifeisguid** [comment] 2020-08-06 21:30
Thank you for looking into that.
I did get to upgrade it and I receive the following.  


[8/6/2020, 4:22:31 PM] [homebridge-magichome-dynamic-platform] 
Found 1 devices.

[8/6/2020, 4:22:32 PM] [homebridge-magichome-dynamic-platform] TypeError: accessoryType[updatedDevice.controller] is not a constructor
at HomebridgeMagichomeDynamicPlatform.discoverDevices (/homebridge/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:245:11)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[8/6/2020, 4:22:32 PM] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0 
Cached devices that were not seen this restart: 0


I have tried to uninstall and reinstall the plugin as well as clear the cache item for it.

Thanks again
Jason




On August 5, 2020 at 3:43 AM, Zacknetic <notifications@github.com> wrote:


@jasonlifeisguid Just to let you know, I've added functionality for magichome dimmers, give it a try and let me know how it goes.

**Comment by Zacknetic** [comment] 2020-08-09 23:28
Go to your config-ui-x>Plugins>Homebridge MagicHome Dynamic Platform> Check the "Prune All Accessories Next Restart (Warning Dangerous)" box>Restart homebridge>Uncheck the "Prune All Accessories Next Restart (Warning Dangerous)" box>Restart again.

These steps have solved issues with the exact same controller and bug in the past. Let me know.
